---
    - name: Bind Services to VIP
      delegate_to: localhost
      register: result
      citrix.adc.citrix_adc_nitro_request:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: update
        resource: lbvserver_service_binding
        validate_certs: false
        attributes:
          name: "{{ lb_vserver  }}"  # Replace with your VIP name
          servicename: "{{ item.service_name }}"
          weight: "{{ item.weight }}"
      loop: "{{ service_bindings }}"
      when: service_bindings | length > 0
      vars:
        service_bindings:
          - service_name: "{{ service_name }}"
            weight: "{{ weight }}"
