---
    - name: Bind Services to VIP
      delegate_to: localhost
      register: result
      citrix.adc.citrix_adc_nitro_request:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: update
        resource: lbvserver_service_binding
        validate_certs: false
        attributes:
          name: "{{ lb_vserver }}"  # Survey input for VIP name
          servicename: "{{ service_name }}"  # Survey input for service name
          weight: "{{ weight }}"  # Survey input for weight
      when: lb_vserver is defined and service_name is defined and weight is defined
