---
    - name: Change weight to load balancing vserver bound to services
      delegate_to: localhost
      citrix.adc.citrix_adc_lb_vserver:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present
        name: "{{ item.0 }}"
        lbvserver_service_binding:
            - name: "{{ item.0 }}"
              servicename: "{{ item.1|first }}"
              weight: "{{ item.1|last }}"
      with_nested:
            - "{{ lb_vserver }}"
            - "{{ service_name.split(",") }}"
