---
    - name: Bind Services to VIP
      delegate_to: localhost
      register: result
      citrix.adc.citrix_adc_nitro_request:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: update
        resource: lbvserver #_service_binding
        validate_certs: false
#        idempotent: true
        name: "{{ item.0 }}"
        attributes:
           name: "{{ item.0 }}"
           servicename: "{{ item.1|split(',')|first }}"
           weight: "{{ item.1|split(',')|last }}"
      with_nested:
            - "{{ lb_vserver }}"
            - "{{ service_name }}"
      when: lb_vserver is defined and service_name is defined 

    - name: Get vserver
      delegate_to: localhost
      register: result
      citrix.adc.citrix_adc_nitro_request:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: get_all
        resource: lbvserver
        validate_certs: false
        name: "{{ item }}"
      with_items:
         - "{{ lb_vserver }}"
