---

    - name: Add VIP to vserver
      delegate_to: localhost
      register: result
      citrix.adc.citrix_adc_nitro_request:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: update
        resource: lbvserver_service_binding 
        validate_certs: false
        idempotent: true
        attributes:
          binding_members:
            - name: "{{ item.0 }}"
              servicename: "{{ item.1 }}"
              weight: "{{ weight_value }}"
      with_nested:
         - "{{ lb_vserver }}"
         - "{{ service_name }}"
