---
    - name: Change weight to load balancing vserver bound to services
      delegate_to: localhost
      citrix.adc.citrix_adc_lb_vserver:
        nsip: "{{ inventory_hostname }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        validate_certs: no
        state: present
        name: "{{ item.0 }}"
        servicebindings:
            - servicename: "{{ item.1|split(',')|first }}"
              weight: "{{ item.1|split(',')|last }}"
      with_nested:
            - "{{ lb_vserver }}"
            - "{{ service_name }}"

    - name: Get vserver
      delegate_to: localhost
      register: result
      citrix_adc_nitro_request:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"
        operation: get
        resource: vserver
        validate_certs: false
        name: "{{ item.0 }}"

